"""New fields in user model

Revision ID: 786a9d6d7d9b
Revises: 7b5766ba8e47
Create Date: 2021-08-13 10:39:39.280764

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "786a9d6d7d9b"
down_revision = "7b5766ba8e47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("about_me", sa.String(length=140), nullable=True)
    )
    op.add_column("user", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_seen")
    op.drop_column("user", "about_me")
    # ### end Alembic commands ###
